// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pip.DataAccess;

#nullable disable

namespace Pip.DataAccess.Migrations
{
    [DbContext(typeof(PipDbContext))]
    [Migration("20250114035828_CleanupInvestmentModel")]
    partial class CleanupInvestmentModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Pip.Model.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AuctionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confirmation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cusip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MaturityDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Par")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reinvestments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityTerm")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cusip", "IssueDate");

                    b.ToTable("Investments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Confirmation = "FOO",
                            Cusip = "912797GL5",
                            IssueDate = new DateOnly(2024, 7, 25),
                            MaturityDate = new DateOnly(2024, 9, 5),
                            Par = 100000,
                            Reinvestments = 0,
                            SecurityTerm = "42-Day",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Confirmation = "BAR",
                            Cusip = "912797KX4",
                            IssueDate = new DateOnly(2024, 6, 18),
                            MaturityDate = new DateOnly(2024, 8, 13),
                            Par = 55000,
                            Reinvestments = 0,
                            SecurityTerm = "8-Week",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Confirmation = "BAZ",
                            Cusip = "912797GK7",
                            IssueDate = new DateOnly(2024, 5, 9),
                            MaturityDate = new DateOnly(2024, 8, 8),
                            Par = 2000400,
                            Reinvestments = 0,
                            SecurityTerm = "13-Week",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
